name: Check cml comment publishing
on:
  pull_request:
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  test_comment:
    environment: test
    runs-on: ubuntu-latest
    env:
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install "https://github.com/iterative/cml#d001-watermark-spaces" --save
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: comment
        run: |
          ./comment.sh "First comment"
          cml comment create --publish --update --watermarkLabel one report.md
          ./comment.sh "Second comment"
          cml comment create --publish --update --watermarkLabel two report.md
