name: Check cml comment publishing
on:
  pull_request:
permissions:
  id-token: write
  contents: write
  pull-requests: write
jobs:
  setup:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: npm install "https://github.com/iterative/cml#d001-watermark-spaces" --save
      - name: comment
        run: |
          ./comment.sh "First comment"
          npx cml comment create --update report.md
