name: Example workflow cml#1173
on: [pull_request, push]
env:
  REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g "https://github.com/iterative/cml#feature-comment-target" --save
      - name: Add commit comment
        run: |
          echo "### Custom commit comment" > ./comment.md
          cml comment create --target='commit' ./comment.md
      - name: Auto comment
        run: |
          echo "### Auto comment" > ./comment.md
          cml comment create ./comment.md
